added an --fflags argument to hoppet-config, for use when compiling with f90; .mod files are now by default installed in PREFIX/include and with non-executable permissions
git-svn-id: svn+ssh://phab.hepforge.org/source/hoppetsvn/trunk@206 27345fc9-8513-0410-81e8-f89a8c677c7e

diff --git a/hoppet-config.in b/hoppet-config.in
--- a/hoppet-config.in
+++ b/hoppet-config.in
@@ -14,13 +14,22 @@ usage()
 This is the tool for determining compiler flags for use with hoppet @VERSION@.
 Usage:
   --prefix     returns the prefix indicating where the code is installed
-  --cxxflags   returns the compilation flags to be used with a C++ programs
+  --cxxflags   returns the compilation flags to be used with C++ programs
+  --fflags     returns the compilation flags to be used with a fortran(90) compiler
   --libs       returns the flags to pass to the linker
 
-NOTE: --libs does not currently provide access to the system f90 libraries 
-      that may be needed if you link a program with a c++ compiler
+NOTE: --libs does not currently provide access to the system f90 libraries, 
+      which may be needed if you link a program with a c++ compiler
 EOF
 exit $1
+}
+
+# wite error messages and exit
+write_error()
+{
+    echo "Error: $1"
+    echo "Use $0 --help for more information"
+    exit 1
 }
 
 # first deal with the case where no argument is passed
@@ -38,8 +47,14 @@ for arg do
 	--cxxflags)
 	  echo -I$installationdir/include
 	  ;;
+	--fflags)
+	  echo -I$installationdir/include
+	  ;;
 	--libs)
 	  echo -L$installationdir/lib -lhoppet_v1
 	  ;;
+	*)
+	    write_error "$arg is not a valid argument"
+	    ;;
     esac
 done
